const playlist = [
    ['Smells Like Teen Spirit', 'Nirvana', '4:39', 'hTWKbfoikeg'],
    ['In The End', 'Linkin Park', '3:38', 'eVTXPUF4Oz4'],
    ['Chop Suey!', 'System Of A Down', '3:27', 'CSvFpBOe8eY'],
    ['Numb', 'Linkin Park', '3:07', 'kXYiU_JCYtU'],
    ['B.Y.O.B.', 'System Of A Down', '4:19', 'zUzd9KyIDrM'],
    ['Boulevard of Broken Dreams', 'Green Day', '4:48', 'Soa3gO7tL-c'],
    ['Bring Me To Life', 'Evanescence', '3:56', '3YxaaGgTQYM'],
    ['Last Resort', 'Papa Roach', '3:18', 'j0lSpNtjPM8'],
    ['Chasing Cars', 'Snow Patrol', '4:28', 'GemKqzILV4w'],
    ['I\'m Not Okay (I Promise)', 'My Chemical Romance', '3:24', 'dhZTNgAs4Fc'],
    ['I Write Sins Not Tragedies', 'Panic! At The Disco', '3:06', 'vc6vs-l5dkc'],
    ['Welcome to the Black Parade', 'My Chemical Romance', '5:14', 'RRKJiM9Njr8'],
    ['Basket Case', 'Green Day', '3:13', 'NUTGr5t3MoY'],
    ['Underdog', 'You Me At Six', '2:27', '5fcAns_hqtM'],
    ['One Step Closer', 'Linkin Park', '2:37', '4qlCC1GOwFw'],
    ['Enter Sandman', 'Metallica', '5:31', 'CD-E-LDc384'],
    ['Learn to Fly', 'Foo Fighters', '4:36', '1VQ_3sBZEm0'],
    ['Fat Lip', 'Sum 41', '3:01', 'CMX2lPum_pg'],
    ['Bodies', 'Drowning Pool', '3:22', '04F4xlWSFh0'],
    ['Flavor of the Weak', 'American Hi-Fi', '3:51', 'uAmINmjpQxw'],
    ['All The Small Things', 'Blink-182', '2:53', '9Ht5RZpzPqw'],
    ['I Miss You', 'Blink-182', '3:50', 's1tAYmMjLdY'],
    ['Throne', 'Bring Me The Horizon', '3:10', 'Ow_qI_F2ZJI'],
    ['Wake Me Up When September Ends', 'Green Day', '4:45', 'NU9JoFKlaZ0'],
    ['Cute Without The \'E\' (Cut From The Team)', 'Taking Back Sunday', '3:32', 'ap0mqwvf7H0'],
    ['Live Outside', 'Enter Shikari', '3:46', 'zSFSbZeShL0'],
    ['A Favor House Atlantic', 'Coheed and Cambria', '3:12', 'pRWjLLpwnOM'],
    ['In Between', 'Beartooth', '3:26', 'j2p_w409y-o'],
    ['Gives You Hell', 'The All-American Rejects', '3:33', 'uxUATkpMQ8A'],
    ['Movies', 'Alien Ant Farm', '3:15', 'LJ2t4jfVTiU-4js'],
    ['Many of Horror', 'Biffy Clyro', '4:22', 'mAh--lH0H3U'],
    ['The Pretender', 'Foo Fighters', '4:31', 'SBjQ9tuuTJQ'],
    ['The Kill', '30 Seconds To Mars', '3:52', '8yvGCAvOAfM'],
    ['Girl All The Bad Guys Want', 'Bowling For Soup', '3:18', 'VGRxmYXi4Io'],
    ['All The Small Things', 'Blink-182', '2:53', '9Ht5RZpzPqw'],
    ['Boys of Summer', 'The Ataris', '4:18', 'Qt6Lkgs0kiU'],
    ['Vindicated', 'Dashboard Confessional', '3:20', 'A94dmLthBHA'],
    ['Way Away', 'Yellowcard', '3:22', 'k4t5qqdP7As'],
    ['Move Along', 'The All-American Rejects', '3:59', 'XleOkGsYgO8'],
    ['Swing, Swing', 'The All-American Rejects', '3:53', 'KtypSRcwIhA'],
    ['The River', 'Good Charlotte', '3:16', 'yVm8PjWCvLg'],
    ['Misery Business', 'Paramore', '3:20', 'aCyGvGEtOwc'],
    ['My Friends Over You', 'New Found Glory', '3:40', 'QfcLcDBII78'],
    ['The Diary of Jane', 'Breaking Benjamin', '3:20', 'DWaB4PXCwFU'],
    ['The Middle', 'Jimmy Eat World', '2:54', 'oKsxPW6i3pM'],
    ['The Kids Aren\'t Alright', 'The Offspring', '3:00', '7iNbnineUCI'],
    ['The Anthem', 'Good Charlotte', '2:53', 'desJKYvdq9A'],
    ['The Bad Touch', 'Bloodhound Gang', '4:05', 'xat1GVnl8-k'],
    ['Teenage Dirtbag', 'Wheatus', '4:07', 'FC3y9llDXuM'],
    ['Teenagers', 'My Chemical Romance', '2:42', 'k6EQAOmJrbw'],
  ];

  export { playlist as default };